version: 0.2

env:
  variables:
    TAG_NAME_PREFIX: "default"
    BUILD_START_TIME: ´date "+%F %T.%N"´
    REPOSITORY_URI: 066862996875.dkr.ecr.eu-central-1.amazonaws.com/hello-world
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $(AWS_REGION))
  build:
    commands:
      - echo Running test...
      - mvn test
  post_build:
    commands:
      - echo Packaging application...
      - mvn package
artifacts:
  files:
    - target/hello-world-*.jar