version: 0.2

env:
  variables:
    VERSION: "default"
    REPOSITORY_URI: 066862996875.dkr.ecr.eu-central-1.amazonaws.com/hello-world
phases:
  pre_build:
    commands:
      - printenv
      - BUILD_START_TIME=$(date "+%d%m%y-%H%M%S")
      - aws --version
      - GIT_HASH=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - ECR_LOGIN_CMD=$(aws ecr get-login --region $AWS_REGION --no-include-email)
      - echo Logging in to Amazon ECR...
      - $ECR_LOGIN_CMD
  build:
    commands:
      - echo Running test...
      - mvn test
  post_build:
    commands:
      - echo Packaging application...
      - mvn package
      - docker build -t $REPOSITORY_URI:$GIT_HASH -t $REPOSITORY_URI:$VERSION-$BUILD_START_TIME -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:$GIT_HASH
      - docker push $REPOSITORY_URI:$VERSION-$BUILD_START_TIME
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$GIT_HASH > imagedefinitions.json
artifacts:
  files:
    - target/hello-world-*.jar
    - imagedefinitions.json
  name: $VERSION-$GIT_HASH-$BUILD_START_TIME
  discard-path: yes