version: 0.2

env:
  variables:
    VERSION: "default"
    REPOSITORY_URI: 066862996875.dkr.ecr.eu-central-1.amazonaws.com/hello-world
phases:
  pre_build:
    commands:
      - export BUILD_START_TIME=´date "+%F %T.%N"´
      - export GIT_HASH=$(git log -1 --pretty=%h)
      - printenv
      - ECR_LOGIN_CMD=$(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(ECR_LOGIN_CMD)
  build:
    commands:
      - echo Running test...
      - mvn test
  post_build:
    commands:
      - echo Packaging application...
      - mvn package
      - docker build -t hello-world/hello-world:${GIT_HASH} -t hello-world/hello-world:${VERSION}-${BUILD_START_TIME} -t hello-world/hello-world:latest
artifacts:
  files:
    - target/hello-world-*.jar
  discard-path: yes