version: 0.2

env:
  variables:
    VERSION: "default"
    BUILD_START_TIME: ´date "+%F %T.%N"´
    GIT_HASH: $(git log -1 --pretty=%h)
    REPOSITORY_URI: 066862996875.dkr.ecr.eu-central-1.amazonaws.com/hello-world
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - printenv
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - echo Running test...
      - mvn test
  post_build:
    commands:
      - echo Packaging application...
      - mvn package
      - docker build -t hello-world/hello-world:${GIT_HASH} -t hello-world/hello-world:${VERSION}-${BUILD_START_TIME} -t hello-world/hello-world:latest
artifacts:
  files:
    - target/hello-world-*.jar
  discard-path: yes